### ISSUE TITLE
Controllers/Page.php 41-48 行没这个文件 ？

### ISSUE THREAD

**Issue by braveryhui** [matyhtf/StatsCenter#2]
Swoole\Loader::addNameSpace('Sdk', PUBLIC_PATH.'/sdk/Sdk/');
        $sdk = new Sdk\Employee(self::APP_ID, self::APP_KEY);
        //跳转到登录平台
        if (empty($_GET['token']))
        {
            $login_url = $sdk->getLoginUrl(WEBROOT . '/page/login/' . $refer);
            $this->http->redirect($login_url);
        }

**Comment by matyhtf** [comment]
这是我们内部使用的一个 员工登录验证的接口，请替换掉这部分代码。
